# Generated by Django 4.1.7 on 2023-03-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.TextField(verbose_name='наименование товара')),
                ('category', models.TextField(verbose_name='категория товара')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='цена товара')),
                ('quantity', models.IntegerField(verbose_name='количество на складе')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
